<?php
/**
 * Created by PhpStorm.
 * User: Anya
 * Date: 30.04.2019
 * Time: 12:40
 */

class Recipe_Model extends Model
{
    public function get_data()
    {
        parent::get_data(); // TODO: Change the autogenerated stub
    }

    public function get_recipe($username, $id)
    {
        session_start();
        if (isset($_SESSION["session_username"])) {

            require_once 'constants.php';
            require_once 'mysqlconnector.php';

            $mySQLConnector = new MySQLConnector(DB_SERVER, DB_USER, DB_PASS, DB_NAME);

            $table = $username . "RecipeTable";

            $query = "SELECT * FROM $table WHERE id = $id";
            $data = $mySQLConnector->getQueryResult($query);


            if (count($data)) {
                foreach ($data as $elem) {
                    $recipe = array(
                        'id' => $elem['id'],
                        'name' => $elem['name'],
                        'img' => $elem['img'],
                        'portions' => $elem['portions'],
                        'calories' => $elem['calories'],
                        'time' => date("h:i", strtotime($elem['time'])),
                        'ingredients' => $elem['ingredients'],
                        'cooking' => $elem['cooking'],
                    );
                }
                return $recipe;
            } else
                header("Location: /error");

        } else
            header("Location: /error");
    }

}